#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maton_machete_MacheteNative */

#ifndef _Included_com_maton_machete_MacheteNative
#define _Included_com_maton_machete_MacheteNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    initialize
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_initialize
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    resize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_resize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_render
  (JNIEnv *, jobject);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_update
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_resume
  (JNIEnv *, jobject);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_start
  (JNIEnv *, jobject);

/*
 * Class:     com_maton_machete_MacheteNative
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maton_machete_MacheteNative_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
